using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WpfApp.Controls
{
    /// <summary>
    /// Interaction logic for AllResourcesControl.xaml
    /// </summary>
    public partial class AllResourcesControl : UserControl
    {
        /// <summary>Initializes a new instance of the <see cref="AllResourcesControl"/> class.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public AllResourcesControl()
        {
            InitializeComponent();
        }
    }
}
