using System.Windows.Controls;

namespace WpfApp.Controls
{
    /// <summary>
    /// Control for displaying all known resources to the application.
    /// </summary>
    public partial class AllResourcesControl : UserControl
    {
        /// <summary>Parameterless constructor.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public AllResourcesControl()
        {
            InitializeComponent();
        }
    }
}
