using System ;
using System.Windows.Controls ;
using System.Windows.Input ;
using NLog ;

namespace WpfControlLibrary1
{
    /// <summary>
    ///     Interaction logic for AssemblyBrowser.xaml
    /// </summary>
    public partial class AssemblyBrowser : UserControl
    {
        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once InternalOrPrivateMemberNotDocumented
        private static Logger _logger = LogManager.GetCurrentClassLogger ( ) ;

        /// <summary>
        ///     Initializes a new instance of the <see cref="AssemblyBrowser" />
        ///     class.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public AssemblyBrowser ( ) { InitializeComponent ( ) ; }

        private void LoadAssemblyList ( object sender , ExecutedRoutedEventArgs e )
        {
            throw new NotImplementedException ( ) ;
        }

        private void CanLoadAssemblyList ( object sender , CanExecuteRoutedEventArgs e ) { }
    }
}