using System.Windows.Controls ;

namespace Controls
{
    /// <summary>
    ///     Interaction logic for DefaultPage.xaml
    /// </summary>
    public partial class DefaultPage : Page
    {
        /// <summary>Initializes a new instance of the <see cref="DefaultPage" /> class.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public DefaultPage ( ) { InitializeComponent ( ) ; }
    }
}