using System.Windows ;
using System.Windows.Controls ;
using NLog ;

namespace WpfApp.Controls
{
    /// <summary>
    ///     Interaction	logic for Registrations.xaml
    /// </summary>
    public partial class Registrations : UserControl
    {
        /// <summary>The lifetime scope property</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LifetimeScopeProperty
        public static readonly DependencyProperty LifetimeScopeProperty =
            Props.LifetimeScopeProperty ;


        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once InternalOrPrivateMemberNotDocumented
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>")]
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger ( ) ;

        /// <summary>
        ///     Initializes a new instance of the <see cref="Registrations" />
        ///     class.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public Registrations ( )
        {
            InitializeComponent ( ) ;
        }

    }
}