using System.Windows.Controls ;

namespace WpfApp.Controls
{
    /// <summary>
    ///     Interaction logic for TypeBrowserPage.xaml
    /// </summary>
    public partial class TypeBrowserPage : Page
    {
        /// <summary>Initializes a new instance of the <see cref="TypeBrowserPage"/> class.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public TypeBrowserPage ( ) { InitializeComponent ( ) ; }
    }
}