# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  submodules: recursive

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs: 
    restoreSolution: '$(solution)'

- task: MsBuildHelperTask@0
  inputs:
    variableName: 'MsBuildAdditionalArguments'
    MsBuildTargetCustom: 'restore;build'
    MsBuildBaseOutputPath: 'StagingDirectory'
    MsBuildOutputPath: 'StagingDirectory'
    TreatWarningsAsError: 'false'
    GerenateDocumentation: 'true'
- task: MSBuild@1
  inputs:
    solution: '**/*.csproj'
    platform: 'x86'
    configuration: 'Release'
    restoreNugetPackages: false
    msbuildArguments: $(MsBuildAdditionalArguments)

- task: CopyFiles@2
  inputs:
    Contents: '**/*.xml'
    TargetFolder: '$(Build.StagingDirectory)/XmlDocs'
    CleanTargetFolder: true
    flattenFolders: true
    preserveTimestamp: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.StagingDirectory)/XmlDocs'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifact: 'XmlDocs'
    publishLocation: 'pipeline'

- task: UploadFilesToSPDocLib@1
  inputs:
    spUrl: 'https://satoridev.sharepoint.com/sites/Dev/Shared%20Documents/Forms/AllItems.aspx?viewpath=%2Fsites%2FDev%2FShared%20Documents%2FForms%2FAllItems.aspx'
    targetFolder: 'XmlDocs'
    login: 'kay@satoridev.onmicrosoft.com'
    password: 'So8XuY#WCu6@b#Y@'
    filesToUpload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'