# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    exclude:
    - azure-pipelines-1.yml
    - azure-pipelines-exo.yml
    - azure-pipelines-1-exo.yml

pool:
  vmImage: 'windows-latest'
  workspace:
    clean: outputs | resources | all 

variables:
  solution: '**/WpfApp.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: recursive

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    createLogFile: true
    logFileVerbosity: 'diagnostic'
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
