# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: MsBuildHelperTask@0
  inputs:
    variableName: 'MsBuildAdditionalArguments'
    MsBuildTargetBuild: true
    MsBuildBaseOutputPath: 'StagingDirectory'
    MsBuildOutputPath: 'StagingDirectory'
    SkipInvalidConfigurations: 'true'
    TreatWarningsAsError: 'false'
    GerenateDocumentation: 'true'
    RunCodeAnalysis: 'false'
    ValidateArchitecture: 'false'
    MvcBuildViews: 'false'
    Precompile: 'false'
    EnableUpdateable: 'false'
- task: MSBuild@1
  inputs:
    solution: '**/*.csproj'
    platform: 'x86'
    configuration: 'Release'
    restoreNugetPackages: true
    msbuildArguments: $(MsBuildAdditionalArguments)