using System.Windows.Input ;

namespace WpfApp
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for Commands
    public static class Commands
    {
        /// <summary>The application settings</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for AppSettings
        public static readonly RoutedUICommand AppSettings =
            new RoutedUICommand ( "Settings" , nameof ( AppSettings ) , typeof ( Commands ) ) ;

        /// <summary>The navigate shell item</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for NavigateShellItem
        public static readonly RoutedUICommand NavigateShellItem =
            new RoutedUICommand (
                                 "Navigate"
                               , nameof ( NavigateShellItem )
                               , typeof ( Commands )
                                ) ;

        /// <summary>The open window</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for OpenWindow
        public static readonly RoutedUICommand OpenWindow =
            new RoutedUICommand ( "Open Window" , nameof ( OpenWindow ) , typeof ( Commands ) ) ;

        /// <summary>The quit application</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for QuitApplication
        public static readonly RoutedUICommand QuitApplication =
            new RoutedUICommand (
                                 "Quit Application"
                               , nameof ( QuitApplication )
                               , typeof ( Commands )
                                ) ;

        /// <summary>The visit type command</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for VisitTypeCommand
        public static readonly RoutedUICommand VisitTypeCommand =
            new RoutedUICommand (
                                 "Visit Type"
                               , nameof ( VisitTypeCommand )
                               , typeof ( Commands )
                                ) ;

        /// <summary>The load assembly list</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LoadAssemblyList
        public static readonly RoutedUICommand LoadAssemblyList =
            new RoutedUICommand ( "Load" , nameof ( LoadAssemblyList ) , typeof ( Commands ) ) ;

        /// <summary>The restart</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Restart
        public static readonly RoutedUICommand Restart =
            new RoutedUICommand ( "Restart" , nameof ( Restart ) , typeof ( Commands ) ) ;

        /// <summary>The dump debug</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DumpDebug
        public static readonly RoutedUICommand DumpDebug =
            new RoutedUICommand ( "Dump Debug" , nameof ( DumpDebug ) , typeof ( Commands ) ) ;

        /// <summary>The filter instances</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for FilterInstances
        public static readonly RoutedUICommand FilterInstances =
            new RoutedUICommand (
                                 "FIlter Instances"
                               , nameof ( FilterInstances )
                               , typeof ( Commands )
                                ) ;

        /// <summary>The load</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Load
        public static readonly RoutedUICommand Load =
            new RoutedUICommand ( "Load" , nameof ( Load ) , typeof ( Commands ) ) ;

        /// <summary>The metadata</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Metadata
        public static readonly RoutedUICommand Metadata =
            new RoutedUICommand ( "Metadata" , nameof ( Metadata ) , typeof ( Commands ) ) ;

        /// <summary>The visit type</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for VisitType
        public static readonly RoutedUICommand VisitType =
            new RoutedUICommand ( "VisitType" , nameof ( VisitType ) , typeof ( Commands ) ) ;
    }
}