using JetBrains.Annotations ;
using KayMcCormick.Test.Common.Fixtures ;
using Tests.Lib.Fixtures ;
using Xunit ;

namespace Tests.CollectionDefinitions
{
    /// <summary></summary>
    /// <seealso cref="WpfApplicationFixture" />
    /// <seealso cref="LoggingFixture" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for WpfApplication
    [ CollectionDefinition ( "WpfApp" ) ] [ UsedImplicitly ]
    public class WpfApplication : //ICollectionFixture < WpfApplicationFixture >
      // , ICollectionFixture < UtilsContainerFixture >
      ICollectionFixture < AppContainerFixture >, ICollectionFixture <GlobalLoggingFixture>
    {
    }
}