using System ;
using System.Collections.Generic ;
using System.Diagnostics ;
using System.Linq ;
using System.Windows ;
using Autofac ;
using Autofac.Core ;
using JetBrains.Annotations ;
using NLog ;
using NLog.Config ;
using NLog.Layouts ;
using NLog.Targets ;
using TestLib.Attributes ;
using TestLib.Fixtures ;
using Tests.Lib.Attributes ;
using Tests.Lib.Fixtures ;
using WpfApp.Core.Interfaces ;
using WpfApp.Core.Logging ;
using WpfApp.Core.Utils ;
using Xunit ;
using Xunit.Abstractions ;

namespace Tests.Main
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ContainerHelperTests
    [ WpfTestApplication ] [ Collection ( "WpfApp" ) ] [ BeforeAfterLogger ] [ LogTestMethod ]
    public class ContainerHelperTests : IClassFixture < LoggingFixture >
    {
        static ContainerHelperTests ( ) { Debug.WriteLine ( "Initialization" ) ; }

        /// <summary>
        ///     Initializes a new instance of the <see cref="T:System.Object" />
        ///     class.
        /// </summary>
        public ContainerHelperTests (
            LoggingFixture        loggingFixture
          , ITestOutputHelper     output
          , WpfApplicationFixture wpfApplicationFixture
        )
        {
            UseLogMethod = LogMethod ;
            UseLogMethod ( $"my logger is type {Logger.GetType ( )}" ) ;
            LoggingFixture = loggingFixture ;
            // WpfApplicationFixture = wpfApplicationFixture ;
            Output                = output ;
            WpfApplicationFixture = wpfApplicationFixture ;
        }

        // ReSharper disable once UnusedAutoPropertyAccessor.Global
        public LoggingFixture LoggingFixture { get ; }

        public WpfApplicationFixture WpfApplicationFixture { get ; }

        public ITestOutputHelper Output { get ; }

        /// <summary>
        ///     Initializes a new instance of the <see cref="T:System.Object" />
        ///     class.
        /// </summary>
        // public ContainerHelperTests ( WpfApplicationFixture WpfApplicationFixture ) { WpfApplicationFixture = WpfApplicationFixture ; }
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger ( ) ;

        public LogDelegates.LogMethod UseLogMethod { get ; }

        private void DumpContainer ( IContainer container )
        {
            foreach ( var comp in container.ComponentRegistry.Registrations )
            {
                var s = $"{comp.Activator.LimitType}: " ;
                foreach ( var service in comp.Services )
                {
                    if ( service is TypedService ts )
                    {
                        Output.WriteLine ( $"service {s} - {ts.ServiceType}" ) ;
                    }
                    else
                    {
                        Output.WriteLine ( $"service is {service}" ) ;
                    }
                }
            }
        }

        // ReSharper disable once UnusedMember.Local
        private void AddTestLoggingTarget ( string setupContainerTest2Name )
        {
            AppLoggingConfigHelper.EnsureLoggingConfigured ( LogMethod ) ;
            var fileTarget = new FileTarget ( "test target" )
                             {
                                 FileName =
                                     Layout.FromString (
                                                        "test-" + setupContainerTest2Name + ".txt"
                                                       )
                             } ;
            LogManager.LogFactory.Configuration.AddTarget ( fileTarget ) ;
            LogManager.LogFactory.Configuration.LoggingRules.Insert (
                                                                     0
                                                                   , new LoggingRule (
                                                                                      "*"
                                                                                    , LogLevel.Trace
                                                                                    , fileTarget
                                                                                     )
                                                                    ) ;
            LogManager.LogFactory.ReconfigExistingLoggers ( ) ;
        }

        private void LogMethod ( string message )
        {
            Debug.WriteLine ( message ) ;
            Output?.WriteLine ( message ) ;
        }

        /// <summary>
        ///     Test resolution of MainWindow
        /// </summary>
        [ WpfFact ]
        [ Trait ( "VS" , "false" ) ]
        private void ResolveMainWindow ( )
        {
            // var customAttribute = Attribute.GetCustomAttribute (
            //                                                     GetType ( )
            //                                                        .GetMethod (
            //                                                                    nameof (
            //                                                                        ResolveMainWindow
            //                                                                    )
            //                                                                   )
            //                                                   , typeof ( AppInitializeAttribute )
            //                                                    ) as AppInitializeAttribute ;

            // customAttribute.MyApp = WpfApplicationFixture.MyApp as App ;

            Assert.NotNull ( WpfApplicationFixture ) ;

            var c = ContainerHelper.SetupContainer ( out var container ) ;
            Assert.NotNull ( c ) ;
            Assert.NotNull ( container ) ;
            // var mainWindow = c.Resolve < MainWindow > ( ) ;
            // Assert.NotNull ( mainWindow ) ;
        }

        /// <summary>Tests the push context.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TestPushContext
        [ WpfFact ]
        public void TestPushContext ( )
        {
            var c = ContainerHelper.SetupContainer ( out var container ) ;
            Assert.NotNull ( c ) ;
            Assert.NotNull ( container ) ;
        }


        /// <summary>Containers the test resolve i menu item list.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ContainerTestResolveIMenuItemList
        [ Fact ] [ UsedImplicitly ] [ Trait ( "Working" , "false" ) ]
        public void ContainerTestResolveIMenuItemList ( )
        {
            var c = ContainerHelper.SetupContainer ( out var container ) ;
            Assert.NotNull ( c ) ;
            Assert.NotNull ( container ) ;
            DumpContainer ( container ) ;
            var menuItemList = c.Resolve < IMenuItemList > ( ) ;
            Assert.NotNull ( menuItemList ) ;
            Assert.NotEmpty ( menuItemList ) ;
            Assert.NotEmpty ( menuItemList.First ( ).Children ) ;
        }

        [ Fact ]
        public void ResolveWindows ( )
        {
            var c = ContainerHelper.SetupContainer ( out var container ) ;
            Assert.NotNull ( c ) ;
            Assert.NotNull ( container ) ;
            var enumerable = c.Resolve < IEnumerable < Lazy < Window > > > ( ) ;
            var l = enumerable.ToList ( ) ;
            Assert.NotEmpty ( l ) ;
            Assert.All ( l , Assert.NotNull ) ;
        }

        [ Fact ]
        public void SetupContainerTest ( )
        {
            var c = ContainerHelper.SetupContainer ( out var container ) ;
            Assert.NotNull ( container ) ;
            Logger.Info ( $"{c}" ) ;
            Assert.NotNull ( c ) ;
        }

        [ Fact ]
        public void SetupContainerTest2 ( )
        {
            AppLoggingConfigHelper.EnsureLoggingConfigured ( ) ;
            // AddTestLoggingTarget ( nameof ( SetupContainerTest2 ) ) ;
            Logger.Warn ( "I am here" ) ;
            var c = ContainerHelper.SetupContainer ( out var container ) ;
            Assert.NotNull ( container ) ;
            Assert.NotNull ( c ) ;
        }

        /// <summary>Tests the resolve top level menu.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TestResolveTopLevelMenu
        [ Fact ]
        public void TestResolveTopLevelMenu ( )
        {
            var c = ContainerHelper.SetupContainer ( out _ ) ;
            var topLevelMenus = c.Resolve < IEnumerable < ITopLevelMenu > > ( ).ToList ( ) ;
            Assert.NotEmpty ( topLevelMenus ) ;
            foreach ( var topLevelMenu in topLevelMenus )
            {
                Logger.Debug ( $"{topLevelMenu.GetXMenuItem ( ).Header}" ) ;
            }
        }
    }
}