using System ;
using NLog ;
using TestLib ;
using Tests.Lib.Attributes ;
using Tests.Lib.Fixtures ;
using WpfApp.Core.Interfaces ;
using WpfApp.Core.Logging ;
using WpfApp1.Menus ;
using Xunit ;
using Xunit.Abstractions ;

namespace Tests.Main
{
    /// <summary></summary>
    [ Collection ( "WpfApp" ) ]
    [ LogTestMethod ] [ BeforeAfterLogger ]
    public class MenuHelperTests : IClassFixture <LoggingFixture>, IDisposable
    {
        // ReSharper disable once UnusedMember.Local
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger ( ) ;

#pragma warning disable 649
        private readonly Func < IMenuItem > _xMenuItemCreator ;
        private XunitTarget _xunitTarget ;
#pragma warning restore 649


        public MenuHelperTests (
            WpfApplicationFixture wpfAppFixture
          , AppContainerFixture   containerFixture
          , UtilsContainerFixture utilsContainerFixture
          , ITestOutputHelper     outputHelper
        )
        {
            AppLoggingConfigHelper.EnsureLoggingConfigured();
            _xunitTarget = new XunitTarget("Xunit") { OutputHelper = outputHelper };
            AppLoggingConfigHelper.AddTarget(_xunitTarget);
        }

        /// <summary>Makes the menu item test.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for MakeMenuItemTest
        [ WpfFact ]
        public void MakeMenuItemTest ( )
        {
            var header = "test" ;
            var arg = _xMenuItemCreator ( ) ;
            arg.Header = header ;
            Assert.NotNull ( arg ) ;
            var item = MenuHelper.MakeMenuItem ( arg ) ;
            Assert.NotNull ( item ) ;
            Assert.Equal ( header , item.Header ) ;
        }

        /// <summary>Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.</summary>
        public void Dispose ( )
        {
            _xunitTarget?.Dispose ( ) ;
        }
    }
}