using System.Collections.Generic ;

namespace WpfApp.Core.Infos
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ComponentInfo
    public class ComponentInfo
    {
        /// <summary>Gets the instances.</summary>
        /// <value>The instances.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Instances
        public IList < InstanceInfo > Instances { get ; } = new List < InstanceInfo > ( ) ;
    }
}