using Tests.Lib.Fixtures ;
using Xunit ;

namespace Tests
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for TestWindowViews
    [Collection("WpfApp")]
    public class TestWindowViews
    {
        /// <summary>Gets the WPF application fixture.</summary>
        /// <value>The WPF application fixture.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for WpfApplicationFixture
        public WpfApplicationFixture WpfApplicationFixture { get ; }

        /// <summary>Gets the application container fixture.</summary>
        /// <value>The application container fixture.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for AppContainerFixture
        public AppContainerFixture AppContainerFixture { get ; }

        /// <summary>Initializes a new instance of the <see cref="T:System.Object" /> class.</summary>
        public TestWindowViews (WpfApplicationFixture wpfApplicationFixture, AppContainerFixture appContainerFixture)
        {
            WpfApplicationFixture = wpfApplicationFixture ;
            AppContainerFixture = appContainerFixture ;
        }

        /// <summary>Tests the container1.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TestContainer1
        public void TestContainer1()
        {

        }
    }
}
