using System.Collections.Generic ;
using System.Collections.ObjectModel ;
using System.Reflection ;

namespace AppShared
{
	/// <summary></summary>
	/// <seealso cref="System.Collections.ObjectModel.ObservableCollection{System.Reflection.Assembly}" />
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for AssemblyList
	public class AssemblyList : ObservableCollection < Assembly >
	{
		/// <summary>Initializes a new instance of the
		///   <see cref="T:System.Collections.ObjectModel.ObservableCollection`1"/>
		///   class.</summary>
		public AssemblyList ( ) { }

		/// <summary>
		///     Initializes a new instance of the
		///     <see cref="T:System.Collections.ObjectModel.ObservableCollection`1" />
		///     class that contains elements copied from the specified list.
		/// </summary>
		/// <param name="list">The list from which the elements are copied.</param>
		/// <exception cref="T:System.ArgumentNullException">
		///     The <paramref name="list" />
		///     parameter cannot be <see langword="null" />.
		/// </exception>
		public AssemblyList ( List < Assembly > list ) : base ( list ) { }

		/// <summary>
		///     Initializes a new instance of the
		///     <see cref="T:System.Collections.ObjectModel.ObservableCollection`1" />
		///     class that contains elements copied from the specified collection.
		/// </summary>
		/// <param name="collection">The collection from which the elements are copied.</param>
		/// <exception cref="T:System.ArgumentNullException">
		///     The
		///     <paramref name="collection" /> parameter cannot be <see langword="null" />.
		/// </exception>
		public AssemblyList ( IEnumerable < Assembly > collection ) : base ( collection ) { }
	}
}