#region header
// Kay McCormick (mccor)
// 
// FileFinder3
// WpfApp1Tests3
// IHasId.cs
// 
// 2020-01-20-4:19 PM
// 
// ---
#endregion

namespace WpfApp.Core.Interfaces
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IHasId
    public interface IHasId
    {
        /// <summary>Gets the object identifier.</summary>
        /// <value>The object identifier.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ObjectId
        long ObjectId { get ; }
    }
}