using Autofac ;

namespace WpfApp.Core.Interfaces
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IHaveLifetimeScope
    public interface IHaveLifetimeScope

    {
        /// <summary>Gets or sets the lifetime scope.</summary>
        /// <value>The lifetime scope.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LifetimeScope
        ILifetimeScope LifetimeScope { get ; }
    }
}