#region header
// Kay McCormick (mccor)
// 
// FileFinder3
// WpfApp1
// IHaveObjectId.cs
// 
// 2020-01-25-12:55 AM
// 
// ---
#endregion
namespace WpfApp.Core.Interfaces
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IHaveObjectId
    public interface IHaveObjectId
    {
        /// <summary>Sets the instance object identifier.</summary>
        /// <value>The instance object identifier.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for InstanceObjectId
        object InstanceObjectId { get ; set ; }
    }
}