using NLog ;

namespace WpfApp.Core.Interfaces
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ILoggerTracker
    public interface ILoggerTracker
    {
        /// <summary>Tracks the logger.</summary>
        /// <param name="loggerName">Name of the logger.</param>
        /// <param name="logger">The logger.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TrackLogger
        void TrackLogger ( string loggerName , ILogger logger ) ;

        /// <summary>Occurs when [logger registered].</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LoggerRegistered
        event LoggerRegisteredEventHandler LoggerRegistered ;
    }
}