using System.Collections ;
using System.Collections.Generic ;

namespace WpfApp.Core.Interfaces
{
    /// <summary></summary>
    /// <seealso cref="System.Collections.Generic.IList{T}" />
    /// <seealso cref="System.Collections.IList" />
    /// <seealso cref="System.Collections.Generic.IReadOnlyList{T}" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IMenuItemList
    // ReSharper disable once PossibleInterfaceMemberAmbiguity
    public interface IMenuItemCollection : IList < IMenuItem > , IList , IReadOnlyList < IMenuItem >
    {
    }
}