namespace WpfApp.Core.Interfaces
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ITopLevelMenu
    public interface ITopLevelMenu
    {
        /// <summary>Gets the x menu item.</summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetXMenuItem
        IMenuItem GetXMenuItem ( ) ;
    }
}