using System ;

namespace WpfApp.Core.Util
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for DebugHelper
    public static class DebugHelper
    {
        /// <summary>Shortens the unique identifier.</summary>
        /// <param name="guid">The unique identifier.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ShortenGuid
        public static string ShortenGuid ( this Guid guid )
        {
            var shortenGuidba = guid.ToByteArray ( ) ;
            return $"{shortenGuidba[ 3 ]:x2}{shortenGuidba[ 2 ]:x2}..{shortenGuidba[ 15 ]:x2}" ;
        }

        /// <summary>Converts to shortguid.</summary>
        /// <param name="newGuid">The new unique identifier.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ToShortGuid
        public static string ToShortGuid ( this Guid newGuid )
        {
            var modifiedBase64 = Convert.ToBase64String ( newGuid.ToByteArray ( ) )
                                        .Replace ( '+' , '-' )
                                        .Replace ( '/' , '_' ) // avoid invalid URL characters
                                        .Substring ( 0 , 22 ) ;
            return modifiedBase64 ;
        }

        /// <summary>Parses the short unique identifier.</summary>
        /// <param name="shortGuid">The short unique identifier.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ParseShortGuid
        public static Guid ParseShortGuid ( string shortGuid )
        {
            var base64 = shortGuid.Replace ( '-' , '+' ).Replace ( '_' , '/' ) + "==" ;
            var bytes = Convert.FromBase64String ( base64 ) ;
            return new Guid ( bytes ) ;
        }
    }
}