#region header
// Kay McCormick (mccor)
// 
// FileFinder3
// CommonTests
// CacheUtils.cs
// 
// 2020-02-03-12:28 AM
// 
// ---
#endregion
using System ;
using System.Linq ;
using System.Reactive.Concurrency ;
using System.Reactive.Linq ;
using System.Windows.Threading ;
using WpfApp.Core.Logging ;

namespace Tests.Lib.Utils
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for CacheUtils
    // ReSharper disable once UnusedType.Global
    public static class CacheUtils
    {
        /// <summary>Setups the cache subscriber.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for SetupCacheSubscriber
        // ReSharper disable once UnusedMember.Global
        public static void SetupCacheSubscriber ( )
        {
            var myCacheTarget = MyCacheTarget.GetInstance ( 1000 ) ;
            myCacheTarget.Cache.SubscribeOn ( Scheduler.Default )
                         .Buffer ( TimeSpan.FromMilliseconds ( 100 ) )
                         .Where ( x => x.Any ( ) )
                         .ObserveOnDispatcher ( DispatcherPriority.Background )
                         .Subscribe (
                                     infos => {
                                         // ReSharper disable once UnusedVariable
                                         foreach ( var logEventInfo in infos )
                                         {
                                         }
                                     }
                                    ) ;
        }
    }
}