using System ;
using System.Reflection ;
using System.Windows ;
using System.Windows.Media ;

namespace Tests.Lib.Utils
{
	/// <summary></summary>
	/// <typeparam name="T"></typeparam>
	/// <seealso cref="System.Windows.Window" />
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for WindowWrap`1
	public class WindowWrap < T > : Window
		where T : Visual
	{
		private readonly T contentInstance ;

		public WindowWrap ( )
		{
			try
			{
				contentInstance = Activator.CreateInstance < T > ( ) ;
				Content         = contentInstance ;
			}
			catch ( TargetInvocationException e )
			{
				throw e.InnerException ;
			}
		}
	}
}