using System ;
using NLog ;

namespace WpfApp.Core.Interfaces.Interfaces
{
    /// <summary></summary>
    /// <seealso cref="System.EventArgs" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for LoggerEventArgs
    public class LoggerEventArgs : EventArgs
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="T:System.EventArgs" />
        ///     class.
        /// </summary>
        public LoggerEventArgs ( ILogger logger ) { Logger = logger ; }

        /// <summary>Gets the logger.</summary>
        /// <value>The logger.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Logger
        // ReSharper disable once UnusedAutoPropertyAccessor.Global
        public ILogger Logger { get ; }
    }
}