using System ;
using System.Reflection ;

namespace Tests.Lib
{
    /// <summary></summary>
    /// <seealso cref="System.Exception" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for UnexpectedPropertyException
    public class UnexpectedPropertyException : Exception
    {
        public string Message { get ; }

        public FieldInfo FieldInfo { get ; }

        public UnexpectedPropertyException ( string message , FieldInfo fieldInfo )
        {
            Message   = message ;
            FieldInfo = fieldInfo ;
        }
    }
}