using System ;
using System.Linq ;
using JetBrains.Annotations ;
using WpfApp.Core.Infos ;

namespace WpfApp.Core.Utils
{
    /// <summary></summary>
    /// <seealso cref="System.IDisposable" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for AttachedContext
    [ UsedImplicitly ]
    public class AttachedContext : IDisposable
    {
        private readonly ContextStack < InfoContext > _contextStack ;
        private readonly InfoContext                  _infoContext ;

        /// <summary>
        ///     Initializes a new instance of the <see cref="AttachedContext" />
        ///     class.
        /// </summary>
        /// <param name="contextStack">The context stack.</param>
        /// <param name="context">The context.</param>
        /// <exception cref="System.ArgumentNullException">contextStack</exception>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public AttachedContext ( ContextStack < InfoContext > contextStack , InfoContext context )
        {
            _contextStack =
                contextStack ?? throw new ArgumentNullException ( nameof ( contextStack ) ) ;
            _infoContext = context ;
            contextStack.Push ( _infoContext ) ;
        }

        /// <summary>
        ///     Performs application-defined tasks associated with freeing, releasing,
        ///     or resetting unmanaged resources.
        /// </summary>
        public void Dispose ( )
        {
            Dispose ( true ) ;
            GC.SuppressFinalize ( this ) ;
        }

        /// <summary>Releases unmanaged and - optionally - managed resources.</summary>
        /// <param name="b">
        ///   <c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
        /// <exception cref="ContextStackException">Empty stack - expected at least one element
        /// or</exception>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Dispose
        protected virtual void Dispose ( bool b )
        {
            if ( ! b )
            {
                return ;
            }

            if ( ! _contextStack.Any ( ) )
            {
                throw new ContextStackException ( "Empty stack - expected at least one element" ) ;
            }

            //Assert.NotEmpty ( contextStack ) ;
            if ( ! _contextStack.Peek ( ).Equals ( _infoContext ) )
            {
                throw new ContextStackException ( "" ) ;
            }

            //Assert.True ( ReferenceEquals ( _infoContext , contextStack.First ( ) ) ) ;
            _contextStack.Pop ( ) ;
        }
    }
}