using System ;
using System.Linq ;
using System.Windows.Controls ;
using JetBrains.Annotations ;
using WpfApp.Core.Interfaces ;

namespace WpfApp.Core.Menus
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for MenuHelper
    public static class MenuHelper
    {
        /// <summary>Makes the menu item.</summary>
        /// <param name="arg">The argument.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for MakeMenuItem
        public static MenuItem MakeMenuItem ( [ NotNull ] IMenuItem arg )
        {
            if ( arg == null )
            {
                throw new ArgumentNullException ( nameof ( arg ) ) ;
            }

            var r = new MenuItem { Header = arg.Header } ;
            if ( arg.Children != null )
            {
                var menuItems = arg.Children.Select ( MakeMenuItem ) ;
                foreach ( var menuItem in menuItems )
                {
                    r.Items.Add ( menuItem ) ;
                }
            }
            else
            {
                r.Command          = arg.Command ;
                r.CommandParameter = arg.CommandParameter ;
                r.CommandTarget    = arg.CommandTarget ;
            }

            return r ;
        }
    }
}