#region header
// Kay McCormick (mccor)
// 
// WpfApp
// WpfApp
// ContainerHelperSettings.cs
// 
// 2020-02-10-12:58 PM
// 
// ---
#endregion
namespace WpfApp.Core.Container
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ContainerHelperSettings
    public class ContainerHelperSettings
    {
        /// <summary>Gets or sets a value indicating whether [do interception].</summary>
        /// <value>
        ///   <see language="1"/> if [do interception]; otherwise, <see language="false"/>.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DoInterception
        // ReSharper disable once UnusedAutoPropertyAccessor.Global
        public bool DoInterception { get ; set ; }

        /// <summary>Gets or sets a value indicating whether [do trace conditional registration].</summary>
        /// <value>
        ///   <see language="1"/> if [do trace conditional registration]; otherwise, <see language="false"/>.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DoTraceConditionalRegistration
        // ReSharper disable once UnusedAutoPropertyAccessor.Global
        public bool DoTraceConditionalRegistration { get ; set ; }
    }
}