using System.Windows ;
using WpfApp.Core.Attributes ;

namespace WpfApp.Controls.Windows
{
    /// <summary>
    ///     Interaction logic for AppSettingsWindow.xaml
    /// </summary>
    [ WindowMetadata ( "Application Settings" ) ]
    public partial class AppSettingsWindow : Window
    {
        /// <summary>Initializes a new instance of the <see cref="AppSettingsWindow"/> class.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public AppSettingsWindow ( ) { InitializeComponent ( ) ; }
    }
}