using System.Windows ;

namespace WpfApp.Controls.Windows
{
    /// <summary>
    ///     Interaction logic for NewWindow.xaml
    /// </summary>
    public partial class NewWindow : Window
    {
        /// <summary>Initializes a new instance of the <see cref="NewWindow"/> class.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public NewWindow ( ) { InitializeComponent ( ) ; }
    }
}