#region header
// Kay McCormick (mccor)
// 
// FileFinder3
// WpfApp1
// BuilderInterceptor.cs
// 
// 2020-01-26-3:30 AM
// 
// ---
#endregion
using System.Reflection ;

namespace WpfApp.Core.Model
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for MethodInvocation
    public class MethodInvocation
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="System.Object" />
        ///     class.
        /// </summary>
        public MethodInvocation (
            MethodInfo method
          , object[]   arguments
          , object     originalReturnValue = null
          , object     returnValue         = null
        )
        {
            Method              = method ;
            Arguments           = arguments ;
            OriginalReturnValue = originalReturnValue ;
            ReturnValue         = returnValue ;
        }

        /// <summary>Gets or sets the method.</summary>
        /// <value>The method.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Method
        // ReSharper disable once UnusedAutoPropertyAccessor.Global
        public MethodInfo Method { get ; }

        /// <summary>Gets or sets the arguments.</summary>
        /// <value>The arguments.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Arguments
        // ReSharper disable once UnusedAutoPropertyAccessor.Global
        public object[] Arguments { get ; }

        /// <summary>Gets or sets the original return value.</summary>
        /// <value>The original return value.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for OriginalReturnValue
        public object OriginalReturnValue { get ; set ; }

        // ReSharper disable once UnusedAutoPropertyAccessor.Global
        /// <summary>Gets or sets the return value.</summary>
        /// <value>The return value.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ReturnValue
        public object ReturnValue { get ; set ; }
    }
}