using System.Collections.ObjectModel ;

namespace WpfApp.Core.Model
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ResourcesModel
    public class ResourcesModel
    {
        /// <summary>Gets or sets the resources collection.</summary>
        /// <value>The resources collection.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ResourcesCollection
        public ObservableCollection < ResourceInfo > ResourcesCollection { get ; } =
            new ObservableCollection < ResourceInfo > ( ) ;
    }
}