using System ;
using System.Diagnostics ;
using System.Reflection ;
using NLog ;
using Xunit.Sdk ;

namespace TestLib.Attributes
{
    /// <summary></summary>
    /// <seealso cref="Xunit.Sdk.BeforeAfterTestAttribute" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for LogTestMethodAttribute
    public class LogTestMethodAttribute : BeforeAfterTestAttribute
    {
        /// <summary>
        /// This method is called after the test method is executed.
        /// </summary>
        /// <param name="methodUnderTest">The method under test</param>
        public override void After ( MethodInfo methodUnderTest )
        {
            if ( methodUnderTest.DeclaringType != null )
            {
                LogManager.GetLogger ( methodUnderTest.DeclaringType.ToString ( ) )
                          .Info ( $"{nameof ( After )} test method {methodUnderTest.Name}" ) ;
            }
        }

        /// <summary>
        /// This method is called before the test method is executed.
        /// </summary>
        /// <param name="methodUnderTest">The method under test</param>
        public override void Before ( MethodInfo methodUnderTest )
        {
            if ( methodUnderTest.DeclaringType != null )
            {
                try
                {
                    LogManager.GetLogger ( methodUnderTest.DeclaringType.ToString ( ) )
                              .Info ( $"{nameof ( Before )} test method {methodUnderTest.Name}" ) ;
                } catch(Exception ex)
                {
                    Debug.WriteLine ( ex.ToString ( ) ) ;
                    
                }
            }
        }
    }
}
