using System ;
using System.Threading.Tasks ;
using System.Windows ;
using JetBrains.Annotations ;
using TestLib.Fixtures ;
using Tests.Lib.Attributes ;
using Xunit ;

namespace Tests.Lib.Fixtures
{
    /// <summary></summary>
    /// <seealso cref="Xunit.IAsyncLifetime" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for WpfApplicationFixture
    [ UsedImplicitly ]
    public class WpfApplicationFixture : IAsyncLifetime
    {
        private readonly WpfApplicationHelper _wpfApplicationHelper = new WpfApplicationHelper ( ) ;

        /// <summary>
        ///     Initializes a new instance of the <see cref="T:System.Object" />
        ///     class.
        /// </summary>
        public WpfApplicationFixture ( ) { }

        /// <summary>Gets or sets the base pack URI.</summary>
        /// <value>The base pack URI.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for BasePackUri
        public Uri BasePackUri => _wpfApplicationHelper.BasePackUri ;

        /// <summary>Gets or sets my application.</summary>
        /// <value>My application.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for MyApp
        public Application MyApp => _wpfApplicationHelper?.MyApp ;

        /// <summary>
        ///     Called immediately after the class has been created, before it is
        ///     used.
        /// </summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for InitializeAsync
        public Task InitializeAsync ( ) { return _wpfApplicationHelper.InitializeAsync ( ) ; }

        /// <summary>
        ///     Called when an object is no longer needed. Called just before
        ///     <see cref="M:System.IDisposable.Dispose" />
        ///     if the class also implements that.
        /// </summary>
        public Task DisposeAsync ( ) { return _wpfApplicationHelper.DisposeAsync ( ) ; }
    }
}