using System ;

namespace WpfApp.Core.Attributes
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for LoggingEntityMetadata
    public class LoggingEntityMetadata
    {
        /// <summary>Gets or sets the type of the logging.</summary>
        /// <value>The type of the logging.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LoggingType
        public Type LoggingType { get ; set ; }
    }
}