using System ;
using System.ComponentModel.Composition ;
using JetBrains.Annotations ;

namespace WpfApp.Core.Attributes
{
    /// <summary></summary>
    /// <seealso cref="System.Attribute" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for WindowMetadataAttribute
    [ MetadataAttribute ]
    [AttributeUsage(AttributeTargets.Class)]
    internal class WindowMetadataAttribute : Attribute
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="System.Object" />
        ///     class.
        /// </summary>
        public WindowMetadataAttribute ( string windowTitle ) { WindowTitle = windowTitle ; }

        /// <summary>Gets the window title.</summary>
        /// <value>The window title.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for WindowTitle
        public string WindowTitle { [ UsedImplicitly ] get ; }
    }
}