#region header
// Kay McCormick (mccor)
// 
// WpfApp
// WpfApp
// LoggingSection.cs
// 
// 2020-02-07-2:57 PM
// 
// ---
#endregion
using System.Configuration ;
using WpfApp.Core.Util ;

namespace WpfApp.Config
{
    /// <summary>Configuration section handler for container helper settings.</summary>
    /// <seealso cref="System.Configuration.ConfigurationSection" />
    [ConfigTarget( typeof ( LoggerSettings ))]
    public class LoggingSection : ConfigurationSection
    {
        private const string doTrace = "DoTraceConditionalRegistration";

        /// <summary>Gets or sets a value indicating whether [do interception].</summary>
        /// <value>
        ///   <c>true</c> if [do interception]; otherwise, <c>false</c>.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DoInterception
        [ConfigurationProperty( "DoInterception", DefaultValue = false, IsRequired = false, IsKey = false)]
        public bool DoInterception { get => ( bool ) this[ "DoInterception" ] ; set => this["DoInterception"] = value; }

        /// <summary>Gets or sets a value indicating whether [do trace conditional registration].</summary>
        /// <value>
        ///   <c>true</c> if [do trace conditional registration]; otherwise, <c>false</c>.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DoTraceConditionalRegistration
        [ConfigurationProperty( doTrace, DefaultValue = false, IsRequired = false, IsKey = false)]
        public bool DoTraceConditionalRegistration
        {
            get => (bool)this[ doTrace ] ;
            set => this[doTrace] = value ;
        }
    }

    public class LoggerSettings
    {

    }
}