using NLog ;
using Tests.Attributes ;
using WpfApp.Core.Context ;
using Xunit ;

namespace Tests.Main.Utils
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for PushContextAttributeTests
    [LogTestMethod ] [ BeforeAfterLogger ][Collection("GeneralPurpose")]
    public class PushContextAttributeTests
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger ( ) ;

        /// <summary>Afters the test.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for AfterTest
        [Fact ]
        [ PushContext ( "context1" ) ]
        public void AfterTest ( ) { }

        /// <summary>Before the test.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for BeforeTest
        [Fact ]
        public void BeforeTest ( ) { }

        /// <summary>Pushes the context attribute test.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for PushContextAttributeTest
        [Fact ]
        [ PushContext ( "test" , "123" ) ]
        public void PushContextAttributeTest ( ) { Logger.Debug ( "test" ) ; }
    }
}